appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: NPFZpyfJD2PUhrfJ6+yvdZazAn+VWpm61LfVAir9OB+7cqB/eC0w9xXE2QnDX9fzptp6T8bSdBHL7FwsPJMeQLS/rFx43WvW0dQq7Yx38TFP5rsdwuidnTS1JOO5cnGLbsmySGaABnpQ/tInHD9Xhu9/28UJ/Z70pSpMabwHhQjd3ll0/j5ccH44U+L5Cu/4BfG/DqwMITg9tZDLkRzHQWA3HpCNpw85dymUtO4MXLcrGuBvTLAvw2yTO4Eif+CSNFqMPg+5TcDgeia9gtjeIbx1M92aqRCThS8+cpvd0cxepABy5vWGQ+WP3cJTGgW7l0G6GtvtDn5ej+q9e4f/CQqXTpMnMaFJf/h0gtoaCJ7Kfmbk5j+G3SXtCBLblABF8Z3fggmewbqz290iblvmhxogKD4n8isUQ2ZJWx1jt5iJRTyw28EDIpvm6RiiT8p+D/GBdZ7toSrNDL2yzVN5DAkzzF0QBU3X4G9YVu3GZdhBM7iVwuXCYrdi0Mn+28sDjyq1effgc4wcy9sxWZYsUpRwC8mS63kq7woYyovq4Zcy6eEP4BkRUEpfvdnhmwhgYODkPMk6Q1gAH5SVG6KaD6DDa1inrIh1WQ382NvXWH4r8DM8GzLhMH6u034IiBK8BI15y8YFvW7gcCdjv5r2YzpUIzI5A+cSTfoU0+yWRsc=}
conda_forge_output_validation: true
bot:
  automerge: true
